7 post api articles article id comments
layla93k/nc-news-backend-project pull request #6
Opened 2023-10-03 13:05 UTC by layla93k

2023-10-03 14:14 UTC, robert112233 requested changes
Cool looks good! 

A few missing tests: 

Status 404 username is not found in the database (psql will throw another error for you to catch) 

400 posting to an invalid id eg. notanumber

404 posting to a non-existent id eg. 9999999

Add these and submit another PR for review! Nice work ⭐️

2023-10-04 08:19 UTC, itsaliabdallah approved these changes
I like that you've thought about seperating your controllers out, maybe thing about seperating them out by article/comments etc instead of the method of the request.

Everything is looking nice, but please consider a refactor as we shouldn't need to have two database queries within a model.

2023-10-04 08:19 UTC, itsaliabdallah commented on Models/post-and-patch-models.js
> +      }
PSQL should throw an error if the articleID is not a valid number.

2023-10-04 08:19 UTC, itsaliabdallah commented on Models/post-and-patch-models.js
> +    const maxArticleQuery = `SELECT MAX(article_id) FROM articles;`
I'm not sure this part of your SQL query is needed or really doing anything right now?
If you make a request with an articleID which is a number and doesn't exist you should recieve an empty array.

2023-10-04 08:19 UTC, itsaliabdallah commented on Models/post-and-patch-models.js
> +    })
As my previous comment about using MAX.
We shouldn't need to make two database queries.

2023-10-04 08:45 UTC, merged